[project]
name = "u7"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cmake>=3.31.6",
    "matplotlib>=3.10.1",
    "notebook>=7.3.3",
    "numpy>=2.1.3",
    "scikit-learn>=1.6.1",
    "tensorflow>=2.19.0",
]
